import type { ParamValue, PresetDefinition } from "../types";
import { bakeFragment } from "./shared";

// The "put it on my website" path — readability of the output is a feature.
export function exportCanvasSnippet(
    preset: PresetDefinition,
    params: Record<string, ParamValue>,
    shareURL: string
): string {
    const frag = bakeFragment(preset, params);
    return `<!-- ${preset.name} — animated shader fill.
     Generated by Shader Fill Studio. Remix: ${shareURL}
     Drop this whole block into any page. The canvas fills its parent element. -->
<canvas id="shader-fill" style="width:100%;height:100%;display:block;"></canvas>
<script>
(() => {
  const canvas = document.getElementById("shader-fill");
  const gl = canvas.getContext("webgl2");
  if (!gl) { canvas.style.background = "#111"; return; }

  const FRAG = \`${frag}\`;
  const VERT = \`#version 300 es
void main() {
  vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));
  gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);
}\`;

  function compile(type, src) {
    const sh = gl.createShader(type);
    gl.shaderSource(sh, src);
    gl.compileShader(sh);
    if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS))
      throw new Error(gl.getShaderInfoLog(sh));
    return sh;
  }
  const prog = gl.createProgram();
  gl.attachShader(prog, compile(gl.VERTEX_SHADER, VERT));
  gl.attachShader(prog, compile(gl.FRAGMENT_SHADER, FRAG));
  gl.linkProgram(prog);
  gl.useProgram(prog);
  const uTime = gl.getUniformLocation(prog, "u_time");
  const uRes = gl.getUniformLocation(prog, "u_resolution");

  // Size to the element × devicePixelRatio (capped at 2)
  const dpr = Math.min(devicePixelRatio || 1, 2);
  function resize() {
    const w = Math.round(canvas.clientWidth * dpr);
    const h = Math.round(canvas.clientHeight * dpr);
    if (canvas.width !== w || canvas.height !== h) {
      canvas.width = w;
      canvas.height = h;
      gl.viewport(0, 0, w, h);
    }
  }
  new ResizeObserver(resize).observe(canvas);
  resize();

  const start = performance.now();
  (function frame() {
    requestAnimationFrame(frame);
    if (document.hidden) return;
    gl.uniform1f(uTime, (performance.now() - start) / 1000);
    gl.uniform2f(uRes, canvas.width, canvas.height);
    gl.drawArrays(gl.TRIANGLES, 0, 3);
  })();
})();
</` + `script>
`;
}
