import type { ParamValue, PresetDefinition } from "../types";
import { bakeFragment } from "./shared";

export function exportThreeJS(
    preset: PresetDefinition,
    params: Record<string, ParamValue>,
    shareURL: string
): string {
    // Three prepends its own #version when glslVersion is set.
    const frag = bakeFragment(preset, params).replace(/^#version 300 es\n/, "");
    return `// ${preset.name} — animated shader fill material for Three.js.
// Generated by Shader Fill Studio. Remix: ${shareURL}
//
// Usage:
//   import { createShaderFillMaterial } from "./shaderFillMaterial.js";
//   const fill = createShaderFillMaterial();
//   const quad = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), fill.material);
//   scene.add(quad);
//   // per frame:  fill.update(clock.getDelta());
//   // on resize:  fill.resize(renderer.domElement.width, renderer.domElement.height);

import * as THREE from "three";

const fragmentShader = \`${frag}\`;

const vertexShader = \`
in vec3 position;
void main() {
    gl_Position = vec4(position, 1.0);
}\`;

export function createShaderFillMaterial() {
    const uniforms = {
        u_time: { value: 0 },
        u_resolution: { value: new THREE.Vector2(1024, 1024) }
    };
    const material = new THREE.RawShaderMaterial({
        glslVersion: THREE.GLSL3,
        fragmentShader,
        vertexShader,
        uniforms,
        depthTest: false,
        depthWrite: false
    });
    return {
        material,
        update(dt) {
            uniforms.u_time.value += dt;
        },
        resize(width, height) {
            uniforms.u_resolution.value.set(width, height);
        }
    };
}
`;
}
